<?php
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

if (isset($_GET['lang']) && in_array($_GET['lang'], ['vi', 'en'])) {
    $_SESSION['lang'] = $_GET['lang'];
}
$lang = $_SESSION['lang'] ?? 'vi';

$translations = [
    'vi' => [
        // Nav
        'home' => 'Trang chủ',
        'rooms' => 'Phòng nghỉ',
        'services' => 'Dịch vụ',
        'reviews' => 'Đánh giá',
        'contact' => 'Liên hệ',
        'hello' => 'Xin chào',
        'admin_panel' => 'Trang Admin',
        'logout' => 'Đăng xuất',
        'login' => 'Đăng nhập',
        'register' => 'Đăng ký',
        'my_bookings' => 'Đặt phòng của tôi',
        'profile' => 'Tài khoản',
        // Hero
        'hero_title' => 'Chào mừng đến <span>Royal Hotel</span>',
        'hero_desc' => 'Tận hưởng kỳ nghỉ tuyệt vời với những căn phòng sang trọng bậc nhất, dịch vụ đẳng cấp 5 sao và không gian yên bình hướng biển.',
        'book_now' => 'Đặt phòng ngay',
        'explore_rooms' => 'Khám phá phòng',
        'hero_stat1_num' => '200+',
        'hero_stat1_label' => 'Phòng sang trọng',
        'hero_stat2_num' => '98%',
        'hero_stat2_label' => 'Khách hài lòng',
        'hero_stat3_num' => '5★',
        'hero_stat3_label' => 'Xếp hạng',
        // Rooms
        'room_types' => 'Các Hạng Phòng',
        'room_tag' => 'Không gian nghỉ dưỡng',
        'room_desc' => 'Lựa chọn không gian nghỉ dưỡng phù hợp với bạn',
        'room_amenities' => 'Tiện nghi phòng',
        'Phòng Standard' => 'Phòng Standard',
        'Phòng tiêu chuẩn với đầy đủ tiện nghi cơ bản, giường đôi, phù hợp cho 1-2 người.' => 'Phòng tiêu chuẩn với đầy đủ tiện nghi cơ bản, giường đôi, phù hợp cho 1-2 người.',
        'Phòng Superior' => 'Phòng Superior',
        'Không gian rộng rãi, thoáng mát, có ban công hướng phố và bồn tắm.' => 'Không gian rộng rãi, thoáng mát, có ban công hướng phố và bồn tắm.',
        'Phòng Deluxe View Biển' => 'Phòng Deluxe View Biển',
        'Phòng sang trọng với view nhìn thẳng ra biển tuyệt đẹp, nội thất tiện nghi.' => 'Phòng sang trọng với view nhìn thẳng ra biển tuyệt đẹp, nội thất tiện nghi.',
        'Phòng Suite (VIP)' => 'Phòng Suite (VIP)',
        'Căn hộ khách sạn hoàng gia, có phòng khách riêng, minibar và nội thất hạng sang.' => 'Căn hộ khách sạn hoàng gia, có phòng khách riêng, minibar và nội thất hạng sang.',
        'Wifi miễn phí' => 'Wifi miễn phí',
        'Điều hòa' => 'Điều hòa',
        'Tivi' => 'Tivi',
        'Tủ lạnh' => 'Tủ lạnh',
        'Bồn tắm' => 'Bồn tắm',
        'available' => 'Còn trống',
        'booked' => 'Đã đặt',
        'night' => '/đêm',
        'book_room' => 'Đặt phòng',
        'view_detail' => 'Xem chi tiết',
        'capacity' => 'Sức chứa',
        'filter_all' => 'Tất cả',
        'filter_standard' => 'Standard',
        'filter_medium' => 'Superior',
        'filter_premium' => 'Premium/VIP',
        // Services
        'our_services' => 'Dịch Vụ Của Chúng Tôi',
        'svc_tag' => 'Tiện ích 5 sao',
        'svc_desc' => 'Trải nghiệm dịch vụ đẳng cấp thế giới ngay tại Royal Hotel',
        // Service Items & Extras
        'Bữa sáng' => 'Bữa sáng',
        'Bữa sáng buffet tại nhà hàng' => 'Bữa sáng buffet tại nhà hàng',
        'Spa & Massage' => 'Spa & Massage',
        'Gói massage thư giãn 60 phút' => 'Gói massage thư giãn 60 phút',
        'Đưa đón sân bay' => 'Đưa đón sân bay',
        'Xe đưa rước sân bay 4 chỗ' => 'Xe đưa rước sân bay 4 chỗ',
        'WiFi Tốc Độ Cao' => 'WiFi Tốc Độ Cao',
        'Internet không giới hạn tại tất cả khu vực' => 'Internet không giới hạn tại tất cả khu vực',
        'Hồ Bơi & Gym' => 'Hồ Bơi & Gym',
        'Bể bơi vô cực và phòng tập gym hiện đại' => 'Bể bơi vô cực và phòng tập gym hiện đại',
        'Nhà Hàng Fine Dining' => 'Nhà Hàng Fine Dining',
        'Ẩm thực Á-Âu với đầu bếp 5 sao' => 'Ẩm thực Á-Âu với đầu bếp 5 sao',
        'Miễn phí' => 'Miễn phí',
        'Theo thực đơn' => 'Theo thực đơn',
        // Reviews
        'reviews_title' => 'Khách Hàng Nói Gì',
        'reviews_tag' => 'Đánh giá thực',
        'reviews_desc' => 'Những chia sẻ thực tế từ khách hàng đã trải nghiệm tại Royal Hotel',
        'write_review' => 'Viết đánh giá',
        // Footer
        'footer_about' => 'Về Royal Hotel',
        'footer_desc' => 'Khách sạn đạt chuẩn 5 sao mang lại trải nghiệm nghỉ dưỡng hoàn hảo nhất cho bạn và gia đình. Thoải mái, sang trọng và tiện nghi.',
        'quick_links' => 'Liên kết nhanh',
        'contact_info' => 'Thông tin liên hệ',
        'copyright' => '© 2026 Royal Hotel. All rights reserved.',
        // Auth
        'login_title' => 'Đăng Nhập',
        'login_subtitle' => 'Chào mừng bạn quay trở lại',
        'username' => 'Tên đăng nhập',
        'password' => 'Mật khẩu',
        'login_btn' => 'Đăng nhập',
        'no_account' => 'Chưa có tài khoản?',
        'register_now' => 'Đăng ký ngay',
        'back_home' => '← Về trang chủ',
        'register_title' => 'Tạo tài khoản',
        'register_subtitle' => 'Tham gia cùng hàng nghìn khách hàng của chúng tôi',
        'fullname' => 'Họ và tên',
        'email' => 'Email',
        'phone' => 'Số điện thoại',
        'confirm_password' => 'Xác nhận mật khẩu',
        'register_btn' => 'Tạo tài khoản',
        'have_account' => 'Đã có tài khoản?',
        'login_now' => 'Đăng nhập ngay',
        'wrong_pass' => 'Sai tài khoản hoặc mật khẩu!',
        'register_success' => 'Đăng ký thành công! Bạn có thể bắt đầu đăng nhập.',
        'user_exists' => 'Tên đăng nhập đã được sử dụng, vui lòng chọn tên khác!',
        'pass_mismatch' => 'Mật khẩu xác nhận không khớp!',
        // Booking
        'complete_booking' => 'Hoàn tất đặt phòng',
        'check_in' => 'Ngày nhận phòng',
        'check_out' => 'Ngày trả phòng',
        'extra_services' => 'Dịch vụ thêm (tùy chọn)',
        'room_cost' => 'Tiền phòng',
        'service_cost' => 'Dịch vụ thêm',
        'total' => 'TỔNG TIỀN',
        'nights' => 'đêm',
        'confirm_book' => 'Xác Nhận Đặt Phòng',
        'book_success' => 'Đặt phòng thành công! Mã đặt phòng:',
        'book_back' => 'Về trang chủ',
        'room_unavailable' => 'Phòng hiện không có sẵn để đặt.',
        // Profile
        'my_profile' => 'Hồ sơ của tôi',
        'edit_profile' => 'Chỉnh sửa thông tin',
        'my_reservations' => 'Đặt phòng của tôi',
        'my_reviews' => 'Đánh giá của tôi',
        'change_password' => 'Đổi mật khẩu',
        'update_success' => 'Cập nhật thành công!',
        'booking_ref' => 'Mã đặt phòng',
        'room_name' => 'Tên phòng',
        'check_in_date' => 'Nhận phòng',
        'check_out_date' => 'Trả phòng',
        'total_price' => 'Tổng tiền',
        'status' => 'Trạng thái',
        'payment_status' => 'Thanh toán',
        'no_bookings' => 'Bạn chưa có đặt phòng nào.',
        'old_password_incorrect' => 'Mật khẩu cũ không đúng!',
        'new_password_min_length' => 'Mật khẩu mới phải có ít nhất 6 ký tự!',
        'password_change_success' => 'Đổi mật khẩu thành công!',
        'review_submitted' => 'Cảm ơn bạn đã gửi đánh giá!',
        'review_error' => 'Vui lòng chọn số sao và nhập nội dung đánh giá!',
        'admin_role' => '👑 Quản trị viên',
        'guest_role' => '🏨 Khách hàng',
        'username_no_change' => 'Tên đăng nhập không thể thay đổi.',
        'current_password' => 'Mật khẩu hiện tại',
        'new_password' => 'Mật khẩu mới',
        'confirm_new_password' => 'Xác nhận mật khẩu mới',
        'new_password_placeholder' => 'Ít nhất 6 ký tự',
        'confirm_new_password_placeholder' => 'Nhập lại mật khẩu mới',
        'change_password_btn' => 'Lưu thay đổi mật khẩu',
        'booking_status_pending' => 'Chờ xử lý',
        'booking_status_confirmed' => 'Đã xác nhận',
        'booking_status_cancelled' => 'Đã hủy',
        'booking_status_completed' => 'Hoàn thành',
        'payment_status_pending' => 'Chờ TT',
        'payment_status_success' => 'Đã TT',
        'payment_status_failed' => 'Thất bại',
        'booking_services' => 'Dịch vụ đã đặt',
        'select_stayed_room' => '-- Chọn phòng bạn đã ở --',
        'rating' => 'Xếp hạng',
        'your_comment' => 'Nhận xét của bạn',
        'comment_placeholder' => 'Chia sẻ trải nghiệm của bạn tại khách sạn...',
        'submit_review_btn' => 'Gửi đánh giá',
        'review_condition_info' => 'Bạn chỉ có thể đánh giá những phòng đã hoàn tất lưu trú.',
        'no_reviews_yet' => 'Bạn chưa có đánh giá nào.',
        // Admin
        'admin_overview' => 'Tổng quan',
        'admin_users' => 'Quản lý User',
        'admin_rooms' => 'Quản lý Phòng',
        'admin_bookings' => 'Quản lý Đặt Phòng',
        'admin_services' => 'Dịch vụ',
        'admin_reviews' => 'Đánh giá',
        'back_to_home' => 'Về trang chủ',
        'dashboard' => 'Bảng điều khiển',
        'total_revenue' => 'Doanh thu',
        'welcome_admin' => 'Chào mừng, Admin!',
        'add_room' => 'Thêm phòng mới',
        'edit' => 'Sửa',
        'delete' => 'Xóa',
        'save' => 'Lưu',
        'cancel' => 'Hủy',
        'confirm' => 'Xác nhận',
        'actions' => 'Thao tác',
        'role' => 'Quyền',
        'created_at' => 'Ngày tạo',
        // New additions for full translation
        'footer_amenities' => 'Tiện Nghi',
        'footer_free_wifi' => 'Wifi miễn phí',
        'footer_parking' => 'Bãi đỗ xe',
        'footer_spa_fitness' => 'Spa & Fitness',
        'footer_restaurant' => 'Nhà hàng',
        'footer_pool' => 'Bể bơi',
        'footer_powered_by' => 'Phát triển bởi PHP & MySQL',
        'contact_call' => 'Gọi điện',
        'contact_zalo' => 'Zalo',
        'contact_messenger' => 'Messenger',
        'contact_tooltip' => 'Đặt phòng nhanh!',
        'booking_success_detail' => 'Chúng tôi sẽ xác nhận đặt phòng của bạn sớm nhất qua email.',
        'select_payment_method' => 'Chọn phương thức thanh toán',
        'payment_bank_transfer' => 'Chuyển khoản',
        'payment_cash' => 'Tiền mặt',
        'payment_qr_info' => 'Quét mã QR hoặc chuyển khoản theo thông tin sau:',
        'account_holder' => 'Chủ tài khoản:',
        'transfer_content' => 'Nội dung:',
        'payment_cash_info' => 'Vui lòng thanh toán bằng tiền mặt tại quầy lễ tân khi nhận/trả phòng.',
        'complete_and_update' => 'Xem lại các đặt phòng',
        'secure_payment' => 'Thanh toán an toàn & bảo mật',
        'past_checkin_date_error' => 'Ngày nhận phòng không thể ở trong quá khứ.',
        'checkout_after_checkin_error' => 'Ngày trả phòng phải sau ngày nhận phòng.',
        'general_error' => 'Có lỗi xảy ra:',
        'no_reviews_fallback' => 'Rất hài lòng với dịch vụ và tiện nghi của khách sạn!',
        'no_reviews_yet_public' => 'Chưa có đánh giá nào.',
    ],
    'en' => [
        // Nav
        'home' => 'Home',
        'rooms' => 'Rooms',
        'services' => 'Services',
        'reviews' => 'Reviews',
        'contact' => 'Contact',
        'hello' => 'Hello',
        'admin_panel' => 'Admin Panel',
        'logout' => 'Logout',
        'login' => 'Login',
        'register' => 'Register',
        'my_bookings' => 'My Bookings',
        'profile' => 'Account',
        // Hero
        'hero_title' => 'Welcome to <span>Royal Hotel</span>',
        'hero_desc' => 'Enjoy an amazing vacation with top-tier luxury rooms, world-class 5-star services, and a peaceful ocean-view atmosphere.',
        'book_now' => 'Book Now',
        'explore_rooms' => 'Explore Rooms',
        'hero_stat1_num' => '200+',
        'hero_stat1_label' => 'Luxury Rooms',
        'hero_stat2_num' => '98%',
        'hero_stat2_label' => 'Satisfied Guests',
        'hero_stat3_num' => '5★',
        'hero_stat3_label' => 'Star Rating',
        // Rooms
        'room_types' => 'Room Categories',
        'room_tag' => 'Luxury Accommodations',
        'room_desc' => 'Find the perfect space tailored to your needs and preferences',
        'room_amenities' => 'Room Amenities',
        'Phòng Standard' => 'Standard Room',
        'Phòng tiêu chuẩn với đầy đủ tiện nghi cơ bản, giường đôi, phù hợp cho 1-2 người.' => 'Standard room with basic amenities, double bed, suitable for 1-2 people.',
        'Phòng Superior' => 'Superior Room',
        'Không gian rộng rãi, thoáng mát, có ban công hướng phố và bồn tắm.' => 'Spacious and airy space with a city-view balcony and bathtub.',
        'Phòng Deluxe View Biển' => 'Deluxe Ocean View Room',
        'Phòng sang trọng với view nhìn thẳng ra biển tuyệt đẹp, nội thất tiện nghi.' => 'Luxury room with a stunning direct ocean view and comfortable furnishings.',
        'Phòng Suite (VIP)' => 'Suite (VIP) Room',
        'Căn hộ khách sạn hoàng gia, có phòng khách riêng, minibar và nội thất hạng sang.' => 'Royal hotel apartment with a private living room, minibar, and luxury furniture.',
        'Wifi miễn phí' => 'Free WiFi',
        'Điều hòa' => 'Air Conditioning',
        'Tivi' => 'TV',
        'Tủ lạnh' => 'Refrigerator',
        'Bồn tắm' => 'Bathtub',
        'available' => 'Available',
        'booked' => 'Booked',
        'night' => '/night',
        'book_room' => 'Book Room',
        'view_detail' => 'View Detail',
        'capacity' => 'Capacity',
        'filter_all' => 'All',
        'filter_standard' => 'Standard',
        'filter_medium' => 'Superior',
        'filter_premium' => 'Premium/VIP',
        // Services
        'our_services' => 'Our Services',
        'svc_tag' => '5-Star Amenities',
        'svc_desc' => 'Experience world-class services right here at Royal Hotel',
        // Service Items & Extras
        'Bữa sáng' => 'Breakfast',
        'Bữa sáng buffet tại nhà hàng' => 'Restaurant buffet breakfast',
        'Spa & Massage' => 'Spa & Massage',
        'Gói massage thư giãn 60 phút' => '60-minute relaxing massage package',
        'Đưa đón sân bay' => 'Airport Transfer',
        'Xe đưa rước sân bay 4 chỗ' => '4-seat airport shuttle service',
        'WiFi Tốc Độ Cao' => 'High-Speed WiFi',
        'Internet không giới hạn tại tất cả khu vực' => 'Unlimited internet in all areas',
        'Hồ Bơi & Gym' => 'Pool & Gym',
        'Bể bơi vô cực và phòng tập gym hiện đại' => 'Infinity pool and modern gym',
        'Nhà Hàng Fine Dining' => 'Fine Dining Restaurant',
        'Ẩm thực Á-Âu với đầu bếp 5 sao' => 'Asian-European cuisine with 5-star chefs',
        'Miễn phí' => 'Free',
        'Theo thực đơn' => 'As per menu',
        // Reviews
        'reviews_title' => 'What Guests Say',
        'reviews_tag' => 'Real Reviews',
        'reviews_desc' => 'Genuine feedback from guests who have experienced Royal Hotel',
        'write_review' => 'Write a Review',
        // Footer
        'footer_about' => 'About Royal Hotel',
        'footer_desc' => 'A 5-star rated hotel offering the perfect vacation experience for you and your family. Comfortable, luxurious, and convenient.',
        'quick_links' => 'Quick Links',
        'contact_info' => 'Contact Info',
        'copyright' => '© 2026 Royal Hotel. All rights reserved.',
        // Auth
        'login_title' => 'Sign In',
        'login_subtitle' => 'Welcome back to Royal Hotel',
        'username' => 'Username',
        'password' => 'Password',
        'login_btn' => 'Sign In',
        'no_account' => "Don't have an account?",
        'register_now' => 'Register Now',
        'back_home' => '← Back to Home',
        'register_title' => 'Create Account',
        'register_subtitle' => 'Join thousands of our guests',
        'fullname' => 'Full Name',
        'email' => 'Email',
        'phone' => 'Phone Number',
        'confirm_password' => 'Confirm Password',
        'register_btn' => 'Create Account',
        'have_account' => 'Already have an account?',
        'login_now' => 'Sign in now',
        'wrong_pass' => 'Invalid username or password!',
        'register_success' => 'Registration successful! You can now log in.',
        'user_exists' => 'Username is already taken, please choose another!',
        'pass_mismatch' => 'Password confirmation does not match!',
        // Booking
        'complete_booking' => 'Complete Your Booking',
        'check_in' => 'Check-in Date',
        'check_out' => 'Check-out Date',
        'extra_services' => 'Extra Services (optional)',
        'room_cost' => 'Room Cost',
        'service_cost' => 'Extra Services',
        'total' => 'TOTAL',
        'nights' => 'nights',
        'confirm_book' => 'Confirm Booking',
        'book_success' => 'Booking successful! Reference ID:',
        'book_back' => 'Back to Home',
        'room_unavailable' => 'This room is currently unavailable.',
        // Profile
        'my_profile' => 'My Profile',
        'edit_profile' => 'Edit Profile',
        'my_reservations' => 'My Reservations',
        'my_reviews' => 'My Reviews',
        'change_password' => 'Change Password',
        'update_success' => 'Updated successfully!',
        'booking_ref' => 'Booking Ref',
        'room_name' => 'Room',
        'check_in_date' => 'Check-in',
        'check_out_date' => 'Check-out',
        'total_price' => 'Total',
        'status' => 'Status',
        'payment_status' => 'Payment',
        'no_bookings' => 'You have no bookings yet.',
        'old_password_incorrect' => 'Old password is not correct!',
        'new_password_min_length' => 'New password must be at least 6 characters!',
        'password_change_success' => 'Password changed successfully!',
        'review_submitted' => 'Thank you for your review!',
        'review_error' => 'Please select a star rating and write a comment!',
        'admin_role' => '👑 Administrator',
        'guest_role' => '🏨 Guest',
        'username_no_change' => 'Username cannot be changed.',
        'current_password' => 'Current Password',
        'new_password' => 'New Password',
        'confirm_new_password' => 'Confirm New Password',
        'new_password_placeholder' => 'At least 6 characters',
        'confirm_new_password_placeholder' => 'Re-type the new password',
        'change_password_btn' => 'Save Password Changes',
        'booking_status_pending' => 'Pending',
        'booking_status_confirmed' => 'Confirmed',
        'booking_status_cancelled' => 'Cancelled',
        'booking_status_completed' => 'Completed',
        'payment_status_pending' => 'Pending',
        'payment_status_success' => 'Paid',
        'payment_status_failed' => 'Failed',
        'booking_services' => 'Booked Services',
        'select_stayed_room' => '-- Select a room you stayed in --',
        'rating' => 'Rating',
        'your_comment' => 'Your Comment',
        'comment_placeholder' => 'Share your experience at our hotel...',
        'submit_review_btn' => 'Submit Review',
        'review_condition_info' => 'You can only review rooms from completed bookings.',
        'no_reviews_yet' => 'You have no reviews yet.',
        // Admin
        'admin_overview' => 'Overview',
        'admin_users' => 'Manage Users',
        'admin_rooms' => 'Manage Rooms',
        'admin_bookings' => 'Manage Bookings',
        'admin_services' => 'Services',
        'admin_reviews' => 'Reviews',
        'back_to_home' => 'Back to Home',
        'dashboard' => 'Dashboard',
        'total_revenue' => 'Revenue',
        'welcome_admin' => 'Welcome, Admin!',
        'add_room' => 'Add New Room',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'save' => 'Save',
        'cancel' => 'Cancel',
        'confirm' => 'Confirm',
        'actions' => 'Actions',
        'role' => 'Role',
        'created_at' => 'Created At',
        // New additions for full translation
        'footer_amenities' => 'Amenities',
        'footer_free_wifi' => 'Free Wifi',
        'footer_parking' => 'Parking',
        'footer_spa_fitness' => 'Spa & Fitness',
        'footer_restaurant' => 'Restaurant',
        'footer_pool' => 'Swimming Pool',
        'footer_powered_by' => 'Powered by PHP & MySQL',
        'contact_call' => 'Call',
        'contact_zalo' => 'Zalo',
        'contact_messenger' => 'Messenger',
        'contact_tooltip' => 'Book now!',
        'booking_success_detail' => 'We will confirm your booking via email shortly.',
        'select_payment_method' => 'Select Payment Method',
        'payment_bank_transfer' => 'Bank Transfer',
        'payment_cash' => 'Cash',
        'payment_qr_info' => 'Scan the QR code or transfer to the following details:',
        'account_holder' => 'Account Holder:',
        'transfer_content' => 'Memo:',
        'payment_cash_info' => 'Please pay in cash at the reception upon check-in or check-out.',
        'complete_and_update' => 'Review Your Bookings',
        'secure_payment' => 'Secure & Encrypted Payment',
        'past_checkin_date_error' => 'Check-in date cannot be in the past.',
        'checkout_after_checkin_error' => 'Check-out date must be after check-in date.',
        'general_error' => 'An error occurred:',
        'no_reviews_fallback' => 'Very satisfied with the service and hotel amenities!',
        'no_reviews_yet_public' => 'No reviews yet.',
    ]
];

function t($key)
{
    global $translations, $lang;
    return $translations[$lang][$key] ?? $key;
}

function switchLangUrl($newLang)
{
    $parsed = parse_url($_SERVER['REQUEST_URI']);
    $query = [];
    if (!empty($parsed['query']))
        parse_str($parsed['query'], $query);
    $query['lang'] = $newLang;
    return $parsed['path'] . '?' . http_build_query($query);
}
?>